# Generated by Django 3.2.2 on 2021-05-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorsPallete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('colorcode', models.CharField(max_length=20, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='LooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('image', models.ImageField(upload_to='images/')),
                ('colors', models.ManyToManyField(blank=True, to='virtual.ColorsPallete')),
            ],
        ),
        migrations.CreateModel(
            name='LipsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('image', models.ImageField(upload_to='images/')),
                ('colors', models.ManyToManyField(blank=True, to='virtual.ColorsPallete')),
            ],
        ),
        migrations.CreateModel(
            name='FaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('image', models.ImageField(upload_to='images/')),
                ('colors', models.ManyToManyField(blank=True, to='virtual.ColorsPallete')),
            ],
        ),
        migrations.CreateModel(
            name='EyesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('image', models.ImageField(upload_to='images/')),
                ('colors', models.ManyToManyField(blank=True, to='virtual.ColorsPallete')),
            ],
        ),
    ]
