# Generated by Django 3.2.3 on 2021-05-27 09:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorspallete',
            name='colorcode',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
